######################################################################
# Automatically generated by qmake (3.0) sam. mai 6 17:40:41 2017
######################################################################

TEMPLATE = app
TARGET = ProjetC
INCLUDEPATH += .

# Input
HEADERS += Animal.h Gazelle.h graphicscene.h Lion.h mainwindow.h
SOURCES += Animal.cpp \
           Gazelle.cpp \
           graphicscene.cpp \
           Lion.cpp \
           main.cpp \
           mainwindow.cpp
QT += widgets
