######################################################################
# Automatically generated by qmake (3.0) mar. mai 29 22:31:44 2018
######################################################################

TEMPLATE = app
TARGET = TpAnimal
INCLUDEPATH += .

# Input
HEADERS += Animal.h Gazelle.h graphicscene.h Lion.h mainwindow.h
SOURCES += Animal.cpp \
           Gazelle.cpp \
           graphicscene.cpp \
           Lion.cpp \
           main.cpp \
           mainwindow.cpp
